services:
  worker-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: worker
    restart: unless-stopped
    ports:
      - "3005:3005"
    networks:
      - app-network
      - shared-network
    depends_on:
      - redis
    environment:
      REDIS_PORT: ${REDIS_PORT}
      REDIS_HOST: redis
      REDIS_PASSWORD: ${REDIS_PASSWORD}

  board:
    build:
      context: ./bull/board
      dockerfile: Dockerfile
    container_name: board
    restart: unless-stopped
    ports:
      - "3001:3001"
    networks:
      - app-network
    depends_on:
      - redis
    environment:
      REDIS_PORT: ${REDIS_PORT}
      REDIS_HOST: redis
      REDIS_PASSWORD: ${REDIS_PASSWORD}

  consumer:
    build:
      context: ./bull/consumers
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - app-network
      - shared-network
    depends_on:
      - redis
    environment:
      REDIS_PORT: ${REDIS_PORT}
      REDIS_HOST: redis
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      URL_API: ${URL_API}
      WORKER_ID: "consumer-${HOSTNAME}"
    deploy:
      replicas: 5

  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
  shared-network:
    driver: bridge
    name: shared-network
    attachable: true
    external: true